# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/32324fce-00d8-4e8b-9f2c-94e22e659ed0";
      fsType = "btrfs";
    };
    "/mnt/data" = {
      device = "/dev/disk/by-uuid/17a40f9b-feba-4116-8c42-fffe1aa1dad5";
      fsType = "btrfs";
    };
    "/var/lib/docker" = {
      device = "/dev/disk/by-label/data";
      fsType = "btrfs";
      options = [ "subvol=docker" ];
    };
    "/home/share" = {
      options = [ "bind" ];
      device = "/mnt/data/share";
    };
    "/home/lucka/Stažené" = {
      options = [ "bind" ];
      device = "/mnt/data/lucka/Stažené";
    };
  };

  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
}
