# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    
    { device = "/dev/disk/by-uuid/14d3bba4-f618-4d7c-a3f8-ee1c8719c5f5";
      fsType = "btrfs";
    };

  fileSystems."/mnt/data" =
    { device = "/dev/disk/by-uuid/a8561e54-d8a9-41ce-a1e0-dc933b63d41b";
      fsType = "ext4";
    };

  fileSystems."/mnt/old-root" =
    { device = "/dev/disk/by-uuid/d14e491e-4f2e-4617-8963-9cd76c555d66";
      fsType = "ext4";
    };

  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
