name: Update packages
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Configure git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Update foxglove-studio
        run: ./update foxglove-studio --commit
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: foxglove-update
          delete-branch: true
          title: 'Foxglove Studio update'
